### ISSUE TITLE
elliptic-curve: cannot multiply `<C as ProjectiveArithmetic>::ProjectivePoint` by `&NonZeroScalar<C>`

### ISSUE THREAD

**Issue by tuankiet65** [RustCrypto/traits#431]
I updated my project to use `k256` v0.7.1, which pulls in `elliptic-curve` v0.8.3. Rebuilding the project throws this error in `elliptic-curve`:

```
error[E0277]: cannot multiply `<C as ProjectiveArithmetic>::ProjectivePoint` by `&NonZeroScalar<C>`
  --> [....]/elliptic-curve-0.8.3/src/ecdh.rs:77:74
   |
77 |     let shared_secret = ProjectivePoint::<C>::from(*public_key.borrow()) * secret_key.borrow();
   |                                                                          ^ no implementation for `<C as ProjectiveArithmetic>::ProjectivePoint * &NonZeroScalar<C>`
   |
   = help: the trait `Mul<&NonZeroScalar<C>>` is not implemented for `<C as ProjectiveArithmetic>::ProjectivePoint`
help: consider further restricting the associated type
   |
75 |     UncompressedPointSize<C>: ArrayLength<u8>, <C as ProjectiveArithmetic>::ProjectivePoint: Mul<&NonZeroScalar<C>>
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

`k256` is built with the following features, if it helps:

```
k256 = { version = "0.7.1", features = ["ecdh", "zeroize", "arithmetic"] }
```

**Comment by tuankiet65** [comment]
Turns out the error is there when using the nightly toolchain (last version that I checked is `rustc 1.50.0-nightly (11c94a197 2020-12-21)`). It compiles fine with the stable toolchain (`rustc 1.48.0 (7eac88abb 2020-11-16)`)

**Comment by rainliu** [comment]
I encountered the same error with nightly. Should we report this issue to rust compiler?

**Comment by tarcieri** [comment]
Looks like another nightly regression similar to this one: https://github.com/RustCrypto/traits/pull/412

I can work around it for the time being, but yeah, this is very strange and might be a compiler bug.

**Comment by tarcieri** [comment]
This should be fixed in v0.8.4 (we also CI on nightly now)

**Comment by tuankiet65** [comment]
Can confirm that `elliptic-curve` v0.8.4 builds fine with `rustc 1.50.0-nightly (bb1fbbf84 2020-12-22)`.
